apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  default.conf: |
    server {
      listen 80;
      location / {
        proxy_pass http://frontend-service:8080;
      }
      location /petclinic/api {
        proxy_pass http://backend-service:9966;
      }
    }